.MODEL SMALL
.DATA

ARR1 DB 9 DUP(?)
ARR2 DB 9 DUP(?)

ADDARR DB 9 DUP(?)
SUBARR DB 9 DUP(?)

AL1MES DB 13,10,10, "ENTER THE ARRAY1 ELEMENTS : $"
AL2MES DB 13,10,10, "ENTER THE ARRAY2 ELEMENTS : $"
ADDL3MES DB 13,10,10, "ADDITION TIME : $"
ADDL4MES DB 13,10,10, "ADDITION OF TWO ARRAY ARE : $"
SUBL5MES DB 13,10,10, "SUBTRACTION OF TWO ARRAY ARE : $"
SUBL6MES DB 13,10,10, "SUBTRACTION OF TWO ARRAY ARE : $"

.CODE
.STARTUP

MOV AH,9
MOV DX,OFFSET AL1MES
INT 21H

MOV SI,0
MOV CX,9

L1:    ; TAKING ELEMENT IN FIRST ARRAY 
   MOV AH,1
   INT 21H
   SUB AL,30H
   MOV ARR1[SI],AL
   INC SI  
   LOOP L1
   
MOV AH,9
MOV DX,OFFSET AL2MES
INT 21H

MOV SI,0
MOV CX,9

L2:    ; TAKING ELEMENT OF SECOND ARRAY
   MOV AH,1
   INT 21H
   SUB AL,30H
   MOV ARR2[SI],AL
   INC SI
   LOOP L2
   
MOV AH,9
MOV DX,OFFSET ADDL3MES
INT 21H

MOV SI,0
MOV CX,9

L3:                   ; HERE WE ARE DOING ADDITION OT TWO ARRAY
   MOV AL,ARR1[SI]
   ADD AL,ARR2[SI]
   MOV ADDARR[SI],AL
   INC SI
   LOOP L3
   
MOV AH,9
MOV DX,OFFSET ADDL4MES
INT 21H

MOV SI,0
MOV CX,9

L4:     ; HERE WE PRINT THE ADDING OF TWO ARRAY
   MOV DL,ADDARR[SI]
   ADD DL,30H
   MOV AH,2
   INT 21H
   INC SI
   LOOP L4
   
MOV AH,9
MOV DX,OFFSET SUBL5MES
INT 21H

MOV SI,0
MOV CX,9

L5:             ; HERE  ADDTION TIME OF TWO ARRAY PERFORM
   MOV AL,ARR1[SI]
   SUB AL,ARR2[SI]
   MOV SUBARR[SI],AL
   INC SI
   LOOP L5
   
MOV AH,9
MOV DX,OFFSET SUBL6MES
INT 21H

MOV SI,0
MOV CX,9

L6:    ; PRINT THE SUBTRACTION OF TWO ARRAY
   MOV DL,SUBARR[SI]
   ADD DL,30H
   MOV AH,2H
   INT 21H
   INC SI
   LOOP L6
   
.EXIT
END



