.MODEL SMALL
.DATA
ARR DB 9 DUP(?)
MES1 DB 13,10,10,"ENTER THE ARRAY ELEMENTS:$"
MES2 DB 13,10,10,"ENTER THE VALUE TO BE SEARCHED :$"
MES3 DB 13,10,10,"VALUE FOUND AT LOCATION :$"
MES4 DB 13,10,10,"VALUE NOT PRESENT IN THE ARRAY :$"

;BEG DB ?
;END DB ?
NUM DB ?

.CODE
.STARTUP

MOV AH,9
MOV DX,OFFSET MES1
INT 21H

MOV SI,0
MOV CX,9

L1:
    MOV AH,1
    INT 21H
    SUB AL,30H
    MOV ARR[SI],AL
    INC SI
    LOOP L1

MOV AH,9
MOV DX,OFFSET MES2
INT 21H

MOV AH,1
INT 21H
SUB AL,30H
MOV NUM,AL

MOV CH,2
MOV BL,0  ; START INDEX
MOV BH,8  ; END INDEX

L2:
   CMP BL,BH
   JAE NOTTHERE 
   
   XOR AX,AX
   MOV AL,BL
   ADD AL,BH ; [ AL = AL+BH]    AND ALSO KNOW THAT
   MOV AH,0  ; AX = AL+BH
   DIV CH    ; [AL = (AL+BH)/2] AND ALSO (AX = AX/2)  SO HERE IS MID VALUE
   MOV AH,0   
   MOV SI,AX ; SI = MID INDEX
   MOV CL,ARR[SI]
   CMP NUM,CL  ; NUM IS MID
   JA GREATER
   JE EQUAL
   DEC AL
   MOV BH,AL
   JMP NEXT
   GREATER:
        INC AL
        MOV BL,AL
   NEXT: LOOP L2
   
NOTTHERE:
   MOV DX,OFFSET MES4
   MOV AH,9
   INT 21H
   JMP STOP
   
EQUAL:
   MOV DX,OFFSET MES3
   MOV AH,9
   INT 21H
   
   MOV DX,SI
   ADD DX,30H
   MOV AH,2
   INT 21H
   
STOP:

.EXIT
END
